language: node_js
node_js:
    - "node"
    - "8"
before_install:
    - npm ci
install:
    - npm install -g codecov
    - npm install -g semantiq
script:
    - npm run qa && codecov
after_script:
    - ./scripts/version
